services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules  # Evita conflitos do node_modules do host
    ports:
      - 9330:9330
      - 3000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env.docker
    command: pnpm start:debug
    depends_on:
      db:
        condition: service_healthy
    
    restart: unless-stopped
  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-app
    volumes:
      - pg_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  node_modules:
  pg_data:

